### ISSUE TITLE
No blur if parent is a UINavigationController

### ISSUE THREAD

**Issue by vocaro** [datinc/DATBlurSegue#1]
Great project, thanks for sharing it!

I've encountered an issue when performing the modal segue on top of a UINavigationController. Although the modal appears, there is no blur. Apparently the modal's background becomes opaque black if the parent is a UINavigationController.

You can reproduce this issue in the sample project easily. Just go to Main.storyboard, select the main view (with the colored squares), and do Editor > Embed In > Navigation Controller. Then build and run, and you should see the problem.

Any thoughts? Thank you.

**Comment by datinc** [comment]
In the perform function of the segue I do the following 

sourceViewController.modalPresentationStyle = UIModalPresentationCurrentContext;

When presenting on top of the navigation controller controller (or any other parent controller) then actual presenting controller needs to have the modalPresentationStyle updated. 

Long story short. I have uploaded a fix to the source code. However this uncovered a new bug. The unwind segue does not work when using the navigation controller

**Comment by vocaro** [comment]
Thanks for the fix! Works great with nav controllers now.
